# Generated by Django 5.2.11 on 2026-02-06 23:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("tate_id", models.IntegerField(default=0)),
                (
                    "name",
                    models.CharField(help_text="Artist's full name", max_length=256),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        help_text="Location of artist's birth",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "birth_year",
                    models.IntegerField(
                        help_text="Year the artist was born", null=True
                    ),
                ),
                (
                    "death_year",
                    models.IntegerField(help_text="Year the artist died", null=True),
                ),
                (
                    "tate_url",
                    models.URLField(
                        help_text="Link to this artist at www.tate.org.uk", null=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID of this artist",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "title",
                    models.CharField(
                        default=None, help_text="Title of the artwork", max_length=512
                    ),
                ),
                (
                    "date_text",
                    models.CharField(
                        help_text="Date artwork was completed (if known)", max_length=64
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        help_text="Link to a thumbnail of this artwork at www.tate.org.uk"
                    ),
                ),
                (
                    "tate_url",
                    models.URLField(
                        help_text="Link to a full image of this artwork at www.tate.org.uk"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID of this artwork",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        help_text="Artist who created this artwork",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to="artworks.artist",
                    ),
                ),
            ],
        ),
    ]
