# Generated by Django 5.2.11 on 2026-02-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artwork",
            options={"ordering": ["title", "artist__name"]},
        ),
        migrations.AddField(
            model_name="artist",
            name="gender",
            field=models.CharField(
                help_text="Binary gender designation", max_length=1, null=True
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="place_of_death",
            field=models.CharField(
                help_text="Location of artist's death", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="acquisition_year",
            field=models.CharField(
                default=None, help_text="Year artwork acquired by Tate", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="credit_line",
            field=models.CharField(
                default=None, help_text="Credit line of the artwork", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="depth",
            field=models.FloatField(default=None, help_text="Depth of the artwork"),
        ),
        migrations.AddField(
            model_name="artwork",
            name="height",
            field=models.FloatField(default=None, help_text="Height of the artwork"),
        ),
        migrations.AddField(
            model_name="artwork",
            name="inscription",
            field=models.CharField(
                default=None, help_text="Inscription of the artwork", max_length=512
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="medium",
            field=models.CharField(
                default=None, help_text="Medium of the artwork", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="units",
            field=models.CharField(
                default=None, help_text="Units for dimensions", max_length=16
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artwork",
            name="width",
            field=models.FloatField(default=None, help_text="Widgth of the artwork"),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="date_text",
            field=models.CharField(
                help_text="Date artwork was completed (if known)", max_length=128
            ),
        ),
    ]
