# Generated by Django 5.2.11 on 2026-02-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0002_alter_artwork_options_artist_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="depth",
            field=models.FloatField(default=0, help_text="Depth of the artwork"),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="height",
            field=models.FloatField(default=0, help_text="Height of the artwork"),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="width",
            field=models.FloatField(default=0, help_text="Widgth of the artwork"),
        ),
    ]
