# Generated by Django 5.2.11 on 2026-02-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0003_alter_artwork_depth_alter_artwork_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="depth",
            field=models.CharField(help_text="Depth of the artwork", max_length=32),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="height",
            field=models.CharField(help_text="Height of the artwork", max_length=32),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="width",
            field=models.CharField(help_text="Widgth of the artwork", max_length=32),
        ),
    ]
