# Generated by Django 5.2.11 on 2026-02-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0004_alter_artwork_depth_alter_artwork_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="search_name",
            field=models.CharField(
                default="abc",
                help_text="Artist's full name normalized for searching",
                max_length=256,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artwork",
            name="search_title",
            field=models.CharField(
                default=None, help_text="Title normalized for searching", max_length=512
            ),
        ),
    ]
