# Generated by Django 5.2.11 on 2026-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0005_artist_search_name_artwork_search_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="search_name",
            field=models.CharField(
                help_text="Artist's full name normalized for searching",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="search_title",
            field=models.CharField(
                default=None,
                help_text="Title normalized for searching",
                max_length=512,
                null=True,
            ),
        ),
    ]
